# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Research Snippets',  url: 'research'}
- {name: 'Mentoring',  url: 'mentor'}
- {name: 'Tutorials',  url: 'tutorial'}
social:
- {icon: 'google', link: 'https://scholar.google.com/citations?user=3IqbycgAAAAJ&hl=en&oi=ao'}
- {icon: 'twitter', link: 'https://x.com/BoltonTran27'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/bolton-h-tran/'}

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'