jobs:
  build:
    runs-on: ubuntu-24.04-x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ruby-build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev

      - name: Install Ruby using ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          cd ruby-build
          sudo ./install.sh
          ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          
      - name: Mark Ruby installation as complete
        run: touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Install bundler and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build
